{% set name = "neurdflib" %}
{% set version = "5.0.1" %}
{% set sha256 = "d34493cee15029ff5db16157429585ff863ba5542675a4d8a94a0da1bc6e3a50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - rdfpipe = rdflib.tools.rdfpipe:main
    - csv2rdf = rdflib.tools.csv2rdf:main
    - rdf2dot = rdflib.tools.rdf2dot:main
    - rdfs2dot = rdflib.tools.rdfs2dot:main
    - rdfgraphisomorphism = rdflib.tools.graphisomorphism:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - isodate
    - pyparsing

  run:
    - python >={{ python_min }}
    - isodate
    - pyparsing
    - html5lib
    - sparqlwrapper

test:
  requires:
    - python {{ python_min }}
  imports:
    - rdflib
    - rdflib.extras
    - rdflib.plugins
    - rdflib.plugins.parsers
    - rdflib.plugins.serializers
    - rdflib.plugins.sparql
    - rdflib.plugins.sparql.results
    - rdflib.plugins.stores
    - rdflib.tools

  commands:
    - rdfpipe --help
    - rdfgraphisomorphism --help

about:
  home: https://github.com/tgbugs/rdflib
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'TEMP RELEASE of new features for RDFLib'
  dev_url: https://github.com/tgbugs/rdflib
  doc_url: https://rdflib.readthedocs.io

extra:
  recipe-maintainers:
    - tgbugs
